from os import name
from django.urls import path
from . import views
from .forms import LoginForm


urlpatterns = [
    
    path('eventmap/<int:user_id>', views.Top.as_view(), name='map'), #関数が必要
    path('login/', views.Login.as_view(), name='login'),
    path('login/', views.Logout.as_view(), name='logout'),
    path('entry/', views.entry, name='entry'),
    path('eventmap/<int:user_id>/1/log', views.maps, name='log1'),
    path('eventmap/<int:user_id>/2/log', views.maps, name='log2'),
    path('eventmap/<int:user_id>/3/log', views.maps, name='log3'),
    path('eventmap/<int:user_id>/4/log', views.maps, name='log4'),
    path('eventmap/<int:user_id>/5/log', views.maps, name='log5'),
    path('eventmap/<int:user_id>/6/log', views.maps, name='log6'),
    path('eventmap/<int:user_id>/7/log', views.maps, name='log7'),
    path('eventmap/<int:user_id>/8/log', views.maps, name='log8'),
    path('eventmap/<int:user_id>/9/log', views.maps, name='log9'),
    path('eventmap/<int:user_id>/10/log', views.maps, name='log10'),
    path('eventmap/<int:user_id>/11/log', views.maps, name='log11'),
    path('eventmap/<int:user_id>/12/log', views.maps, name='log12'),
    path('eventmap/<int:user_id>/13/log', views.maps, name='log13'),
    path('eventmap/<int:user_id>/14/log', views.maps, name='log14'),
    path('eventmap/<int:user_id>/15/log', views.maps, name='log15'),
    path('eventmap/<int:user_id>/16/log', views.maps, name='log16'),
    path('eventmap/<int:user_id>/17/log', views.maps, name='log17'),
    path('eventmap/<int:user_id>/18/log', views.maps, name='log18'),
    path('eventmap/<int:user_id>/19/log', views.maps, name='log19'),
    path('eventmap/<int:user_id>/20/log', views.maps, name='log20'),
    path('eventmap/<int:user_id>/21/log', views.maps, name='log21'),
    path('eventmap/<int:user_id>/22/log', views.maps, name='log22'),
    path('eventmap/<int:user_id>/23/log', views.maps, name='log23'),
    path('eventmap/<int:user_id>/24/log', views.maps, name='log24'),
    path('eventmap/<int:user_id>/25/log', views.maps, name='log25'),
    path('eventmap/<int:user_id>/26/log', views.maps, name='log26'),
    path('eventmap/<int:user_id>/27/log', views.maps, name='log27'),
    path('eventmap/<int:user_id>/28/log', views.maps, name='log28'),
    path('eventmap/<int:user_id>/29/log', views.maps, name='log29'),
    path('eventmap/<int:user_id>/30/log', views.maps, name='log30'),
    path('eventmap/<int:user_id>/31/log', views.maps, name='log31'),
    path('eventmap/<int:user_id>/32/log', views.maps, name='log32'),
    path('eventmap/<int:user_id>/33/log', views.maps, name='log33'),
    path('eventmap/<int:user_id>/34/log', views.maps, name='log34'),
    path('eventmap/<int:user_id>/35/log', views.maps, name='log35'),
    path('eventmap/<int:user_id>/36/log', views.maps, name='log36'),
    path('eventmap/<int:user_id>/37/log', views.maps, name='log37'),
    path('eventmap/<int:user_id>/38/log', views.maps, name='log38'),
    path('eventmap/<int:user_id>/39/log', views.maps, name='log39'),
    path('eventmap/<int:user_id>/40/log', views.maps, name='log40'),
    path('eventmap/<int:user_id>/41/log', views.maps, name='log41'),
    path('eventmap/<int:user_id>/42/log', views.maps, name='log42'),
    path('eventmap/<int:user_id>/43/log', views.maps, name='log43'),
    path('eventmap/<int:user_id>/44/log', views.maps, name='log44'),
    path('eventmap/<int:user_id>/45/log', views.maps, name='log45'),
    path('eventmap/<int:user_id>/46/log', views.maps, name='log46'),
    path('eventmap/<int:user_id>/47/log', views.maps, name='log47'),
    path('eventmap/forms', views.forms, name='forms'),
    path('eventmap/howto', views.howto, name='howto'),
    path('edit/<int:num>/<int:user_id>', views.edit, name='edit'),
    path('delete/<int:num>/<int:user_id>', views.delete, name='delete'),
    path('eventmap/<int:user_id>/global', views.public, name='public'),
    path('eventmap/news', views.news, name='news'),
]