# Generated by Django 3.1.2 on 2021-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=4)),
                ('place', models.CharField(max_length=50)),
                ('startrip', models.DateField()),
                ('endtrip', models.DateField()),
                ('photo', models.ImageField(upload_to='media/')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
