# Generated by Django 3.1.2 on 2021-06-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmap', '0004_visit_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='public',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
